//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenQuangNamK22CNTT2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctdonhang
    {
        public int orderdetails_id { get; set; }
        public Nullable<int> donhang_id { get; set; }
        public Nullable<int> tranhve_id { get; set; }
        public int soluong { get; set; }
        public decimal gia { get; set; }
    
        public virtual donhang donhang { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
